DATA:
    ROOT: '/home/ubuntu/data/datasets/MAFW/data/frames/frames/frames'
    TRAIN_FILE: '/home/ubuntu/data/datasets/MAFW/Train_Test_Set/single/no_caption/set_2/train_converted.txt'
    VAL_FILE: '/home/ubuntu/data/datasets/MAFW/Train_Test_Set/single/no_caption/set_2/test_converted.txt'
    DATASET: MAFW
    NUM_FRAMES: 16
    NUM_DIVIDE: 4
    NUM_CLASSES: 7
    LABEL_LIST: '/home/ubuntu/data/datasets/AU-CLIP-final_01/AU-CLIP/labels2prompt/mafw_7_AUE_labels.csv'
MODEL:
    ARCH: ViT-B/16
    PRETRAINED: None
TRAIN:
    BATCH_SIZE: 16
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-6
AU:
  ENABLED: True
  NUM_AU: 18
  LAMBDA: 0.05
  POSW_OPTION: "distinct" #distinct,minor
  LABEL_PATH: '/home/ubuntu/data/datasets/AU_MAFW.txt'
